spring:
  h2:
    console:
      enable: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:payment
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      dll:
        auto: update
  cloud:
    stream:
      kafka:
        binder:
          autoCreateTopics: true
          brokers: localhost:9892
          configuration:
            value:
              deserializar: io.confluent.kafka.serializers.KafkaAvroDeserializer
              serializar: io.confluent.kafka.serializers.KafkaAvroSerializer
            key:
              deserializar: io.confluent.kafka.serializers.KafkaAvroDeserializer
              serializar: io.confluent.kafka.serializers.KafkaAvroSerializer
      bindings:
        checkout-created-input:
          destination: streaming.ecommerce.checkout.created
          contentType: application/*+avro
          consumer:
            use-native-encoding: true
        payment-paid-output:
          destination: streaming.ecommerce.payment.paid
          contentType: application/*+avro
          group: ${spring.application.name}
          producer:
            use-native-decoding: true